### ISSUE TITLE
打扰您了，请问这个博客有模板吗谢谢

### ISSUE THREAD

**Issue by jerry609** [Vanilla-Beauty/Vanilla-Beauty.github.io#1]
打扰您了，很喜欢你的博客的样子，请问这个博客有模板吗谢谢

**Comment by Vanilla-Beauty** [comment]
框架是hexo: https://hexo.io/zh-cn/docs/index.html
主题是 https://github.com/probberechts/hexo-theme-cactus

**Comment by jerry609** [comment]
非常感谢
